const FOUR_SPACES_STRING = "    ";
const TWO_SPACES_STRING = "  ";
const ONE_SPACE_STRING = " ";
const NEW_LINE = "\n";
const SEMI_COLON = ";";

export {FOUR_SPACES_STRING, TWO_SPACES_STRING, ONE_SPACE_STRING, NEW_LINE, SEMI_COLON};